server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        highlight_sql: true

  security:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

# JWT 설정
jwt:
  secret: mySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLongAndSecure123!
  access-token-validity-minutes: 60

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs              # OpenAPI 스펙(JSON) 문서 경로
  swagger-ui:
    path: /swagger-ui.html          # Swagger UI 접근 경로
    try-it-out-enabled: true        # Try it out 버튼 활성화 (UI에서 API 실행 가능)
    #filter: true                    # 엔드포인트 검색 필터 표시
    display-request-duration: true  # API 호출 시간(ms) 표시
    persist-authorization: true     # 인증 토큰/헤더 LocalStorage에 저장하여 새로고침 후 유지

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.example.board: debug
    org.springdoc: info